fred_sys/urls.py
from django.contrib import admin
from django.urls import path, include
from sys_web import views


urlpatterns = [path("admin/", admin.site.urls), path("", include("sys_web.urls"))]

sys_web/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("avaliacriterios", views.avaliacriterios, name="avaliacriterios"),
    path("avaliarum", views.avaliarum, name="avaliarum"),
    path("avaliardois", views.avaliardois, name="avaliardois"),
    path("avaliartres", views.avaliartres, name="avaliartres"),
    path("resultado", views.resultado, name="resultado"),
] 

sys_web/models.py
from django.db import models

# Create your models here.


class Dados(models.Model):
    criterio1 = models.CharField(max_length=20)
    criterio2 = models.CharField(max_length=20)
    criterio3 = models.CharField(max_length=20)

    decisor1 = models.CharField(max_length=20)
    decisor2 = models.CharField(max_length=20)
    decisor3 = models.CharField(max_length=20)

    alternativa1 = models.CharField(max_length=20)
    alternativa2 = models.CharField(max_length=20)
    alternativa3 = models.CharField(max_length=20)



class Criterios(models.Model):
    d1c1c2 = models.IntegerField()
    d1c1c3 = models.IntegerField()
    d1c2c3 = models.IntegerField()

    d2c1c2 = models.IntegerField()
    d2c1c3 = models.IntegerField()
    d2c2c3 = models.IntegerField()

    d3c1c2 = models.IntegerField()
    d3c1c3 = models.IntegerField()
    d3c2c3 = models.IntegerField()

class Avaliarum(models.Model):
    c1a1a2 = models.IntegerField()
    c1a1a3 = models.IntegerField()
    c1a2a3 = models.IntegerField()

    c2a1a2 = models.IntegerField()
    c2a1a3 = models.IntegerField()
    c2a2a3 = models.IntegerField()

    c3a1a2 = models.IntegerField()
    c3a1a3 = models.IntegerField()
    c3a2a3 = models.IntegerField()

class Avaliardois(models.Model):
    c1a1a2 = models.IntegerField()
    c1a1a3 = models.IntegerField()
    c1a2a3 = models.IntegerField()

    c2a1a2 = models.IntegerField()
    c2a1a3 = models.IntegerField()
    c2a2a3 = models.IntegerField()

    c3a1a2 = models.IntegerField()
    c3a1a3 = models.IntegerField()
    c3a2a3 = models.IntegerField()

class Avaliartres(models.Model):
    c1a1a2 = models.IntegerField()
    c1a1a3 = models.IntegerField()
    c1a2a3 = models.IntegerField()

    c2a1a2 = models.IntegerField()
    c2a1a3 = models.IntegerField()
    c2a2a3 = models.IntegerField()

    c3a1a2 = models.IntegerField()
    c3a1a3 = models.IntegerField()
    c3a2a3 = models.IntegerField()

sys_web/forms.py
from django import forms
from django.forms import (formset_factory, modelformset_factory)

from .models import *


class DadosForm(forms.ModelForm):
    class Meta:
        model = Dados
        fields = ("criterio1", "criterio2", "criterio3","decisor1", "decisor2", "decisor3","alternativa1", "alternativa2", "alternativa3",)


class CriteriosForm(forms.ModelForm):
    class Meta:
        model = Criterios
        fields = ("d1c1c2","d1c1c3","d1c2c3","d2c1c2","d2c1c3","d2c2c3","d3c1c2","d3c1c3","d3c2c3",)


class AvaliarumForm(forms.ModelForm):
    class Meta:
        model = Avaliarum
        fields = ("c1a1a2","c1a1a3","c1a2a3","c2a1a2","c2a1a3","c2a2a3","c3a1a2","c3a1a3","c3a2a3",)


class AvaliardoisForm(forms.ModelForm):
    class Meta:
        model = Avaliardois
        fields = ("c1a1a2","c1a1a3","c1a2a3","c2a1a2","c2a1a3","c2a2a3","c3a1a2","c3a1a3","c3a2a3",)


class AvaliartresForm(forms.ModelForm):
    class Meta:
        model = Avaliartres
        fields = ("c1a1a2","c1a1a3","c1a2a3","c2a1a2","c2a1a3","c2a2a3","c3a1a2","c3a1a3","c3a2a3",)

sys_web/views.py
from django.shortcuts import render, redirect
from django.views import generic
from itertools import combinations

from .forms import *
from .models import *
from .utils import *


def home(request):
    template_name = 'sys_web/home.html'
    heading_message = 'Decisores'
    if request.method == "POST":
        form_decisor = DadosForm(request.POST)
        if form_decisor.is_valid():
            decisor_conteudo = form_decisor.save()
            return redirect("avaliacriterios")


    return render(request, template_name, {'heading': heading_message})


def avaliacriterios(request):
    template_name = 'sys_web/avaliacriterios.html'
    heading_message = 'Decisores'
    dados = Dados.objects.order_by('-pk')[0]
    if request.method == "POST":
        form_decisor = CriteriosForm(request.POST)
        if form_decisor.is_valid():
            decisor_conteudo = form_decisor.save()
            return redirect("avaliarum")

    return render(request, template_name, {'heading': heading_message, 'dados':dados})

def avaliarum(request):
    template_name = 'sys_web/avaliarum.html'

    dados = Dados.objects.order_by('-pk')[0]
    heading_message = dados.decisor1
    if request.method == "POST":
        form_decisor = AvaliarumForm(request.POST)
        if form_decisor.is_valid():
            decisor_conteudo = form_decisor.save()
            return redirect("avaliardois")

    return render(request, template_name, {'heading': heading_message, 'dados':dados})

def avaliardois(request):
    template_name = 'sys_web/avaliardois.html'

    dados = Dados.objects.order_by('-pk')[0]
    heading_message = dados.decisor2
    if request.method == "POST":
        form_decisor = AvaliardoisForm(request.POST)
        if form_decisor.is_valid():
            decisor_conteudo = form_decisor.save()
            return redirect("avaliartres")

    return render(request, template_name, {'heading': heading_message, 'dados':dados})

def avaliartres(request):
    template_name = 'sys_web/avaliartres.html'

    dados = Dados.objects.order_by('-pk')[0]
    heading_message = dados.decisor3
    if request.method == "POST":
        form_decisor = AvaliartresForm(request.POST)
        if form_decisor.is_valid():
            decisor_conteudo = form_decisor.save()
            return redirect("resultado")

    return render(request, template_name, {'heading': heading_message, 'dados':dados})


def resultado(request):
    template_name = 'sys_web/resultado.html'
    heading_message = "Resultado"
    dados = Dados.objects.order_by('-pk')[0]
    cr = Criterios.objects.order_by('-pk')[0]
    a_um = Avaliarum.objects.order_by('-pk')[0]
    a_do = Avaliardois.objects.order_by('-pk')[0]
    a_tr = Avaliartres.objects.order_by('-pk')[0]


    peso_decisor_um = normalizar([[0, cr.d1c1c2, cr.d1c1c3],[cr.d1c1c2*-1,0,cr.d1c2c3],[cr.d1c1c3*-1,cr.d1c2c3*-1,0]])
    peso_decisor_dois = normalizar([[0, cr.d2c1c2, cr.d2c1c3],[cr.d2c1c2*-1,0,cr.d2c2c3],[cr.d2c1c3*-1,cr.d2c2c3*-1,0]])
    peso_decisor_tres = normalizar([[0, cr.d3c1c2, cr.d3c1c3],[cr.d3c1c2*-1,0,cr.d3c2c3],[cr.d3c1c3*-1,cr.d3c2c3*-1,0]])

    peso_final = peso_criterios([peso_decisor_um, peso_decisor_dois, peso_decisor_tres])
  

    aval_um_c1 = normalizar_alternativas([[0,a_um.c1a1a2, a_um.c1a1a3],[a_um.c1a1a2*-1, 0, a_um.c1a2a3],[a_um.c1a1a3*-1, a_um.c1a2a3*-1,0]])
    aval_um_c2 = normalizar_alternativas([[0,a_um.c2a1a2, a_um.c2a1a3],[a_um.c2a1a2*-1, 0, a_um.c2a2a3],[a_um.c2a1a3*-1, a_um.c2a2a3*-1,0]])
    aval_um_c3 = normalizar_alternativas([[0,a_um.c3a1a2, a_um.c3a1a3],[a_um.c3a1a2*-1, 0, a_um.c3a2a3],[a_um.c3a1a3*-1, a_um.c3a2a3*-1,0]])


    aval_do_c1 = normalizar_alternativas([[0,a_do.c1a1a2, a_do.c1a1a3],[a_do.c1a1a2*-1, 0, a_do.c1a2a3],[a_do.c1a1a3*-1, a_do.c1a2a3*-1,0]])
    aval_do_c2 = normalizar_alternativas([[0,a_do.c2a1a2, a_do.c2a1a3],[a_do.c2a1a2*-1, 0, a_do.c2a2a3],[a_do.c2a1a3*-1, a_do.c2a2a3*-1,0]])
    aval_do_c3 = normalizar_alternativas([[0,a_do.c3a1a2, a_do.c3a1a3],[a_do.c3a1a2*-1, 0, a_do.c3a2a3],[a_do.c3a1a3*-1, a_do.c3a2a3*-1,0]])


    aval_tr_c1 = normalizar_alternativas([[0,a_tr.c1a1a2, a_tr.c1a1a3],[a_tr.c1a1a2*-1, 0, a_tr.c1a2a3],[a_tr.c1a1a3*-1, a_tr.c1a2a3*-1,0]])
    aval_tr_c2 = normalizar_alternativas([[0,a_tr.c2a1a2, a_tr.c2a1a3],[a_tr.c2a1a2*-1, 0, a_tr.c2a2a3],[a_tr.c2a1a3*-1, a_tr.c2a2a3*-1,0]])
    aval_tr_c3 = normalizar_alternativas([[0,a_tr.c3a1a2, a_tr.c3a1a3],[a_tr.c3a1a2*-1, 0, a_tr.c3a2a3],[a_tr.c3a1a3*-1, a_tr.c3a2a3*-1,0]])


    soma_alte_c1 = soma_alternativa_por_criterio([aval_um_c1, aval_do_c1, aval_tr_c1])
    soma_alte_c2 = soma_alternativa_por_criterio([aval_um_c2, aval_do_c2, aval_tr_c2])
    soma_alte_c3 = soma_alternativa_por_criterio([aval_um_c3, aval_do_c3, aval_tr_c3])



    resultado_um = multiplica_final([soma_alte_c1, soma_alte_c2, soma_alte_c3], peso_final)
    resultado = [(dados.alternativa1,resultado_um[0]),(dados.alternativa2,resultado_um[1]), (dados.alternativa3,resultado_um[2])]

    resultado.sort(key=lambda x: x[1] ,reverse=True)


    return render(request, template_name, {'heading': heading_message, 'dados':dados, 'resultado':resultado, 'peso_final':peso_final})

sys_web/templates/sys_web/alternativas.html
{% extends "sys_web/base.html" %}

{% block container %}
{% if heading %}
<h3>{{heading}}</h3>
{% endif %}
<form class="form-horizontal" method="POST" action="">
    {% csrf_token %}
{{ formset.management_form }}
{% for form in formset %}
<div class="row form-row spacer">
    <div class="col-2">
        <label>{{form.name.label}}</label>
    </div>
    <div class="col-4">
        <div class="input-group">
            {{form.name}}
            <div class="input-group-append">
                <button class="btn btn-success add-form-row">+</button>
            </div>
        </div>
    </div>
</div>
{% endfor %}
<div class="row spacer">
    <div class="col-4 offset-2">
        <button type="submit" class="btn btn-block btn-primary">Create</button>
    </div>
</div>
</form>
{% endblock %}

{% block custom_js %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script type="text/javascript">
function updateElementIndex(el, prefix, ndx) {
    var id_regex = new RegExp('(' + prefix + '-\\d+)');
    var replacement = prefix + '-' + ndx;
    if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
    if (el.id) el.id = el.id.replace(id_regex, replacement);
    if (el.name) el.name = el.name.replace(id_regex, replacement);
}
function cloneMore(selector, prefix) {
    var newElement = $(selector).clone(true);
    var total = $('#id_' + prefix + '-TOTAL_FORMS').val();
    newElement.find(':input').each(function() {
        var name = $(this).attr('name')
        if(name) {
            name = name.replace('-' + (total-1) + '-', '-' + total + '-');
            var id = 'id_' + name;
            $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
        }
    });
    total++;
    $('#id_' + prefix + '-TOTAL_FORMS').val(total);
    $(selector).after(newElement);
    var conditionRow = $('.form-row:not(:last)');
    conditionRow.find('.btn.add-form-row')
    .removeClass('btn-success').addClass('btn-danger')
    .removeClass('add-form-row').addClass('remove-form-row')
    .html('-');
    return false;
}
function deleteForm(prefix, btn) {
    var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
    if (total > 1){
        btn.closest('.form-row').remove();
        var forms = $('.form-row');
        $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
        for (var i=0, formCount=forms.length; i<formCount; i++) {
            $(forms.get(i)).find(':input').each(function() {
                updateElementIndex(this, prefix, i);
            });
        }
    }
    return false;
}
$(document).on('click', '.add-form-row', function(e){
    e.preventDefault();
    cloneMore('.form-row:last', 'form');
    return false;
});
$(document).on('click', '.remove-form-row', function(e){
    e.preventDefault();
    deleteForm('form', $(this));
    return false;
});

</script>
{% endblock %}

sys_web/templates/sys_web/avaliacriterios.html
{% extends "sys_web/base.html" %}

{% block container %}
{% if heading %}
<h3>{{heading}}</h3>
{% endif %}

<table style="margin-top: -40px">
     <form method="post">
          {% csrf_token %}
  <tr>

    <th>Decisor 1 - {{dados.decisor1}}</th> 

  </tr>
  <tr>
    <td>Criterio 1 - {{dados.criterio1}}   X   Criterio 2  -  {{dados.criterio2}}</td>

  </tr>

  <tr>
  
    <td>
    <input type="radio" name="d1c1c2" value=-3> Absolutamente Pior&ensp;
 
      <input type="radio" name="d1c1c2" value=-2> Muito Pior&ensp;

      <input type="radio" name="d1c1c2" value=-1> Pior&ensp;

        <input type="radio" name="d1c1c2" value=0> equivalente&ensp;
 
        <input type="radio" name="d1c1c2" value=1> Melhor&ensp;

        <input type="radio" name="d1c1c2" value=2> Muito melhor&ensp;

        <input type="radio" name="d1c1c2" value=3> Absolu. melhor&ensp;

      </td>


  </tr>
</br></br>

  <tr>
    <td >Criterio 1 - {{dados.criterio1}}   X   Criterio 3  -  {{dados.criterio3}}</td>

  </tr>

  <tr>

    <td >
    <input type="radio" name="d1c1c3" value=-3> Absolutamente Pior&ensp;
 
      <input type="radio" name="d1c1c3" value=-2> Muito Pior&ensp;

      <input type="radio" name="d1c1c3" value=-1> Pior&ensp;

        <input type="radio" name="d1c1c3" value=0> equivalente&ensp;
 
        <input type="radio" name="d1c1c3" value=1> Melhor&ensp;

        <input type="radio" name="d1c1c3" value=2> Muito melhor&ensp;

        <input type="radio" name="d1c1c3" value=3> Absolu. melhor&ensp;

      </td>


  </tr>

  <tr>
    <td>Criterio 2 - {{dados.criterio2}}   X   Criterio 3  -  {{dados.criterio3}}</td>

  </tr>

  <tr>

    <td>
    <input type="radio" name="d1c2c3" value=-3> Absolutamente Pior&ensp;
 
      <input type="radio" name="d1c2c3" value=-2> Muito Pior&ensp;

      <input type="radio" name="d1c2c3" value=-1> Pior&ensp;

        <input type="radio" name="d1c2c3" value=0> equivalente&ensp;
 
        <input type="radio" name="d1c2c3" value=1> Melhor&ensp;

        <input type="radio" name="d1c2c3" value=2> Muito melhor&ensp;

        <input type="radio" name="d1c2c3" value=3> Absolu. melhor&ensp;
      </td>

  </tr>
</br>
</table>

<table style="margin-top: -50px">
  <tr>

    <th>Decisor 2 - {{dados.decisor2}}</th> 

  </tr>
  <tr>
    <td>Criterio 1 - {{dados.criterio1}}   X   Criterio 2  -  {{dados.criterio2}}</td>

  </tr>

  <tr>

    <td>
    <input type="radio" name="d2c1c2" value=-3> Absolutamente Pior&ensp;
 
      <input type="radio" name="d2c1c2" value=-2> Muito Pior&ensp;

      <input type="radio" name="d2c1c2" value=-1> Pior&ensp;

        <input type="radio" name="d2c1c2" value=0> equivalente&ensp;
 
        <input type="radio" name="d2c1c2" value=1> Melhor&ensp;

        <input type="radio" name="d2c1c2" value=2> Muito melhor&ensp;

        <input type="radio" name="d2c1c2" value=3> Absolu. melhor&ensp;

      </td>

  </tr>
</br></br>

  <tr>
    <td>Criterio 1 - {{dados.criterio1}}   X   Criterio 3  -  {{dados.criterio3}}</td>

  </tr>

  <tr>

    <td>
    <input type="radio" name="d2c1c3" value=-3> Absolutamente Pior&ensp;
 
      <input type="radio" name="d2c1c3" value=-2> Muito Pior&ensp;

      <input type="radio" name="d2c1c3" value=-1> Pior&ensp;

        <input type="radio" name="d2c1c3" value=0> equivalente&ensp;
 
        <input type="radio" name="d2c1c3" value=1> Melhor&ensp;

        <input type="radio" name="d2c1c3" value=2> Muito melhor&ensp;

        <input type="radio" name="d2c1c3" value=3> Absolu. melhor&ensp;

      </td>

  </tr>
</br>
</br>
  <tr>
    <td>Criterio 2 - {{dados.criterio2}}   X   Criterio 3  -  {{dados.criterio3}}</td>

  </tr>

  <tr>

    <td>
    <input type="radio" name="d2c2c3" value=-3> Absolutamente Pior &ensp;
 
      <input type="radio" name="d2c2c3" value=-2> Muito Pior&ensp;

      <input type="radio" name="d2c2c3" value=-1> Pior&ensp;

        <input type="radio" name="d2c2c3" value=0> equivalente&ensp;
 
        <input type="radio" name="d2c2c3" value=1> Melhor&ensp;

        <input type="radio" name="d2c2c3" value=2> Muito melhor&ensp;

        <input type="radio" name="d2c2c3" value=3> Absolu. melhor&ensp;

      </td>

  </tr>
</br>


</table>


<table style="margin-top: -50px">
  <tr>

    <th>Decisor 3 - {{dados.decisor3}}</th> 

  </tr>
  <tr>
    <td>Criterio 1 - {{dados.criterio1}}   X   Criterio 2  -  {{dados.criterio2}}</td>

  </tr>

  <tr>

    <td>
    <input type="radio" name="d3c1c2" value=-3> Absolutamente Pior&ensp;
 
      <input type="radio" name="d3c1c2" value=-2> Muito Pior&ensp;

      <input type="radio" name="d3c1c2" value=-1> Pior&ensp;

        <input type="radio" name="d3c1c2" value=0> equivalente&ensp;
 
        <input type="radio" name="d3c1c2" value=1> Melhor&ensp;

        <input type="radio" name="d3c1c2" value=2> Muito melhor&ensp;

        <input type="radio" name="d3c1c2" value=3> Absolu. melhor&ensp;

      </td>


  </tr>
</br></br>

  <tr>
    <td>Criterio 1 - {{dados.criterio1}}   X   Criterio 3  -  {{dados.criterio3}}</td>

  </tr>

  <tr>

    <td>
    <input type="radio" name="d3c1c3" value=-3> Absolutamente Pior&ensp;
 
      <input type="radio" name="d3c1c3" value=-2> Muito Pior&ensp;

      <input type="radio" name="d3c1c3" value=-1> Pior&ensp;

        <input type="radio" name="d3c1c3" value=0> equivalente&ensp;
 
        <input type="radio" name="d3c1c3" value=1> Melhor&ensp;

        <input type="radio" name="d3c1c3" value=2> Muito melhor&ensp;

        <input type="radio" name="d3c1c3" value=3> Absolu. melhor&ensp;

      </td>


  </tr>
</br>
</br>
  <tr>
    <td>Criterio 2 - {{dados.criterio2}}   X   Criterio 3  -  {{dados.criterio3}}</td>

  </tr>

  <tr>

    <td>
    <input type="radio" name="d3c2c3" value=-3> Absolutamente Pior&ensp;
 
      <input type="radio" name="d3c2c3" value=-2> Muito Pior&ensp;

      <input type="radio" name="d3c2c3" value=-1> Pior&ensp;

        <input type="radio" name="d3c2c3" value=0> equivalente&ensp;
 
        <input type="radio" name="d3c2c3" value=1> Melhor&ensp;

        <input type="radio" name="d3c2c3" value=2> Muito melhor&ensp;

        <input type="radio" name="d3c2c3" value=3> Absolu. melhor&ensp;

      </td>


  </tr>
</br>

 
</table>
  <button type="submit" class="btn btn-default" style="margin-top: 20px">Processar</button>
 </form>
{% endblock %}

sys_web/templates/sys_web/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <style type="text/css">
        .spacer{
            margin-top:25px;
        }
    </style>
    {% block custom_css %}{% endblock %}
    <title>SapevoWeb</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">SapevoWeb </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <div class="row spacer"></div>
        <div class="row offset-2">
            <div class="col-12">
                {% block container %}
                {% endblock %}
            </div>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    {% block custom_js %}{% endblock %}
</body>

</html>

sys_web/templates/sys_web/home.html
{% extends "sys_web/base.html" %}

{% block container %}
{% if heading %}
<h3>SAPEVO-M</h3>
{% endif %}

     <form method="post">
          {% csrf_token %}

  <legend>Agentes Decisores:</legend>
  <div class="username">
    <label for="uname">Decisor 1:</label>
    <input type="text" id="id_decisor1" name="decisor1" required
      minlength="3" maxlength="16"
      placeholder="" />
  </div>

  <div class="username">
    <label for="uname">Decisor 2:</label>
    <input type="text" id="id_decisor2" name="decisor2" required
      minlength="3" maxlength="16"
      placeholder="" />
  </div>

  <div class="username">
    <label for="uname">Decisor 3:</label>
    <input type="text" id="id_decisor3" name="decisor3" required
      minlength="3" maxlength="16"
      placeholder="" />
  </div>




<fieldset>
  <legend>Critérios:</legend>

  <div class="username">
    <label for="uname">Criterio 1:</label>
    <input type="text" id="id_criterio1" name="criterio1" required
      minlength="3" maxlength="16"
      placeholder="" />
  </div>

  <div class="username">
    <label for="uname">Criterio 2:</label>
    <input type="text" id="id_criterio2" name="criterio2" required
      minlength="3" maxlength="16"
      placeholder="" />
  </div>

  <div class="username">
    <label for="uname">Criterio 3:</label>
    <input type="text" id="id_criterio3" name="criterio3" required
      minlength="3" maxlength="16"
      placeholder="" />
  </div>

</fieldset>


<fieldset>
  <legend>Alternativas:</legend>

  <div class="username">
    <label for="uname">Alternativa 1:</label>
    <input type="text" id="alternativa1" name="alternativa1" required
      minlength="3" maxlength="16"
      placeholder="" />
  </div>

  <div class="username">
    <label for="uname">alternativa 2:</label>
    <input type="text" id="alternativa2" name="alternativa2" required
      minlength="3" maxlength="16"
      placeholder="" />
  </div>

  <div class="username">
    <label for="uname">Alternativa 3:</label>
    <input type="text" id="alternativa3" name="alternativa3" required
      minlength="3" maxlength="16"
      placeholder="" />
  </div>
    <button type="submit" class="btn btn-default">Cadastrar</button>

  </form>

</br>
<div style="margin-top: 40px">

</div>

<address>
Escrito por <a href="mailto:luiz_frederico@id.uff.br">Luiz Frederico</a>.<br> 
Orientado por:  Profº Carlos Francisco Simões Gomes<br>
Universidade Federal Fluminense<br>
</address>

{% endblock %}

{% block custom_js %}
{% endblock %}